apiVersion: v1 # Version de Kubernetes que se esta usando para cración de obejtos
kind: Pod # Tipo de objeto: pod, deployment ...
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis:5.0.4
      volumeMounts:
        - mountPath: /redis-master
          name: config
  volumes:
    - name: config
      configMap:
        name: example-redis-config
        items:
          - key: redis-config
            path: redis.conf
